version: "3"
services:
  eurekaadminserver:
    build:
      context: ./Eureka_Admin_Server
    ports:
      - "8761:8761"
  eurekaclientone:
    build:
      context: ./Eureka_Client_One
    ports:
      - "8080-8085:8040"
    depends_on:
      - eurekaadminserver
  eurekaclienttwo:
    build:
      context: ./Eureka_Client_Two
    ports:
      - "8086-8090:8050"
    depends_on:
      - eurekaadminserver
